---
openapi: 3.0.1
info:
  title: 일정관리 API Document
  description: '내일배움캠프 스프링 숙련과제 일정관리 앱 Develop

    '
  contact:
    email: mxcoogi@gmail.com
  version: '1.0'
servers:
  - url: http://localhost:8080
tags:
  - name: 테스트
    description: 테스트 관련 API
paths:
  "/users":
    put:
      tags:
        - user-controller
      summary: 회원정보 수정
      description: 회원정보를 수정합니다 (현재 이름만 업데이트)
      operationId: updateUser
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/UpdateRequestDto"
        required: true
      responses:
        '200':
          description: 업데이트 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
        '401':
          description: 로그인을 해주세요
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
    delete:
      tags:
        - user-controller
      summary: 회원 삭제
      description: 비밀번호 확인후 회원 삭제합니다
      operationId: deleteUser
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/DeleteRequestDto"
        required: true
      responses:
        '204':
          description: 삭제 성공
        '400':
          description: 잘못된 요청
        '404':
          description: 사용자를 찾을 수 없음
        '409':
          description: 비밀번호가 틀립니다 권한이 없습니다
  "/schedules/{scheduleId}":
    get:
      tags:
        - schedule-controller
      summary: 일정 단건 조회
      description: 일정 식별자로 단일 일정 조회
      operationId: findSchedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '401':
          description: 로그인 필요
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '404':
          description: 일정을 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
    put:
      tags:
        - schedule-controller
      summary: 일정 수정
      description: 일정의 제목과 내용을 수정합니다
      operationId: updateSchedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/UpdateRequestDto"
        required: true
      responses:
        '200':
          description: 수정 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '401':
          description: 로그인을 해야합니다
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '404':
          description: 일정을 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '409':
          description: 권한이 없습니다
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
    delete:
      tags:
        - schedule-controller
      summary: 일정 삭제
      description: 일정 식별자로 일정을 삭제합니다
      operationId: deleteSchedule
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 삭제 성공
        '400':
          description: 잘못된 요청
        '401':
          description: 로그인이 필요합니다
        '404':
          description: 일정을 찾을 수 없음
        '409':
          description: 비밀번호가 틀립니다. 권한이 없습니다.
  "/schedules/{scheduleId}/comments/{commentId}":
    put:
      tags:
        - comment-controller
      summary: 댓글 수정
      description: 특정 스케줄의 특정 댓글을 수정합니다
      operationId: updateComment
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/CommentRequestDto"
        required: true
      responses:
        '200':
          description: 수정 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '401':
          description: 로그인이 필요합니다
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '404':
          description: 일정을 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '409':
          description: 권한이 없습니다. 비밀
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
    delete:
      tags:
        - comment-controller
      summary: 댓글 삭제
      description: 댓글을 삭제 합니다
      operationId: deleteComment
      parameters:
        - name: commentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 삭제 성공
        '400':
          description: 잘못된 요청
        '401':
          description: 로그인이 필요합니다
        '404':
          description: 일정을 찾을 수 없음
        '409':
          description: 권한이 없습니다. 비밀번호가 틀립니다.
  "/schedules":
    get:
      tags:
        - schedule-controller
      summary: 일정 전체 조회
      description: 일정을 전체 조회합니다
      operationId: findAllSchedule
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
      responses:
        '200':
          description: 조회 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleAllResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleAllResponseDto"
        '401':
          description: 로그인이 필요함
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleAllResponseDto"
    post:
      tags:
        - schedule-controller
      summary: 일정 생성
      description: 일정을 생성 합니다
      operationId: createSchedule
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/CreateRequestDto"
        required: true
      responses:
        '201':
          description: 일정 생성 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '401':
          description: 이메일과 비밀번호가 맞지 않음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/ScheduleResponseDto"
  "/schedules/{scheduleId}/comments":
    post:
      tags:
        - comment-controller
      summary: 댓글 생성
      description: 특정 일정에 댓글을 작성합니다
      operationId: createComment
      parameters:
        - name: scheduleId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/CommentRequestDto"
        required: true
      responses:
        '200':
          description: 댓글 작성 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '401':
          description: 로그인 필요합니다
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
        '404':
          description: 일정을 찾을 수 없습니다
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/CommentResponseDto"
  "/auth/sign-up":
    post:
      tags:
        - auth-controller
      summary: 회원가입
      description: 이메일, 비밀번호, 이름을 등록해 회원가입 합니다
      operationId: signUp
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/SignUpRequestDto"
        required: true
      responses:
        '201':
          description: 회원가입 성공
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/SignUpResponseDto"
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/SignUpResponseDto"
        '409':
          description: 이미 존재하는 이메일
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/SignUpResponseDto"
  "/auth/logout":
    post:
      tags:
        - auth-controller
      summary: 로그아웃
      description: 이메일, 비밀번호로 로그인 합니다
      operationId: login
      responses:
        '204':
          description: 로그아웃 성공
        '401':
          description: 로그인해주세요
  "/auth/login":
    post:
      tags:
        - auth-controller
      summary: 로그인
      description: 이메일, 비밀번호로 로그인 합니다
      operationId: login_1
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              "$ref": "#/components/schemas/LoginRequestDto"
        required: true
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json;charset=UTF-8:
              schema:
                type: integer
                format: int64
        '400':
          description: 잘못된 요청
          content:
            application/json;charset=UTF-8:
              schema:
                type: integer
                format: int64
        '401':
          description: 이메일과 비밀번호가 맞지 않음
          content:
            application/json;charset=UTF-8:
              schema:
                type: integer
                format: int64
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                type: integer
                format: int64
  "/users/{userId}":
    get:
      tags:
        - user-controller
      summary: 회원 조회
      description: 회원 식별자로 회원 조회
      operationId: findUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 완료
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
        '401':
          description: 로그인을 해주세요
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
        '404':
          description: 사용자를 찾을 수 없음
          content:
            application/json;charset=UTF-8:
              schema:
                "$ref": "#/components/schemas/UserResponseDto"
  "/test":
    get:
      tags:
        - 테스트
      summary: 테스트메서드
      description: 테스트메서드입니다
      operationId: test
      responses:
        '200':
          description: 테스트 성공
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
        '500':
          description: 서버 에러
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
components:
  schemas:
    UpdateRequestDto:
      required:
        - updateUserName
      type: object
      properties:
        updateUserName:
          type: string
    UserResponseDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        userName:
          type: string
        userEmail:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CommentResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        contents:
          type: string
        userName:
          type: string
        scheduleId:
          type: integer
          format: int64
        createAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ScheduleResponseDto:
      type: object
      properties:
        scheduleId:
          type: integer
          format: int64
        scheduleTitle:
          type: string
        scheduleContents:
          type: string
        userName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        commentList:
          type: array
          items:
            "$ref": "#/components/schemas/CommentResponseDto"
    CommentRequestDto:
      type: object
      properties:
        contents:
          type: string
    CreateRequestDto:
      required:
        - scheduleTitle
      type: object
      properties:
        scheduleTitle:
          type: string
        scheduleContents:
          type: string
    SignUpRequestDto:
      required:
        - userName
        - userPassword
      type: object
      properties:
        userName:
          type: string
        userEmail:
          type: string
        userPassword:
          type: string
    SignUpResponseDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        userName:
          type: string
        userEmail:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    LoginRequestDto:
      required:
        - userPassword
      type: object
      properties:
        userEmail:
          type: string
        userPassword:
          type: string
    ScheduleAllResponseDto:
      type: object
      properties:
        totalPage:
          type: integer
          format: int32
        scheduleResponseDtoList:
          type: array
          items:
            "$ref": "#/components/schemas/ScheduleResponseDto"
    DeleteRequestDto:
      required:
        - userPassword
      type: object
      properties:
        userPassword:
          type: string
